name: Build
on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install npm
      run: npm install -g npm@7
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build:prod
